# Generated by Django 4.1.5 on 2023-08-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soumission',
            name='projet',
            field=models.FileField(upload_to='soumissions'),
        ),
    ]
