# Generated by Django 4.1.5 on 2023-08-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiant', '0002_alter_soumission_projet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soumission',
            name='projet',
            field=models.FileField(upload_to='projets'),
        ),
    ]
