# Generated by Django 4.1.5 on 2023-08-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEcole', '0003_devoir'),
    ]

    operations = [
        migrations.AddField(
            model_name='devoir',
            name='profil',
            field=models.ImageField(blank=True, default='12.png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(' ETUDIANT', 'Etudiant'), ('ENSEIGNANT', 'Enseignant'), (' ADMINISTRATEUR', 'Administrateur')], max_length=30, verbose_name='Rôle'),
        ),
    ]
