# Generated by Django 4.1.5 on 2023-08-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEcole', '0005_remove_devoir_profil_user_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profil',
            field=models.ImageField(blank=True, default='12.png', upload_to='projets'),
        ),
    ]
