# Generated by Django 4.1.5 on 2023-08-21 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('enseignant', models.ForeignKey(limit_choices_to={'role': 'Enseignant'}, on_delete=django.db.models.deletion.CASCADE, related_name='cours_enseignant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
